version: "3.8"

services:
  backend:
    build: ./nexdom-backend
    image: nexdom-backend-image  # Nome personalizado da imagem
    container_name: nexdom-backend-container  # Nome personalizado do contêiner
    ports:
      - "8080:8080"
    networks:
      - nexdom-net

  frontend:
    build: ./nexdom-frontend
    image: nexdom-frontend-image  # Nome personalizado da imagem
    container_name: nexdom-frontend-container  # Nome personalizado do contêiner
    ports:
      - "9000:9000"
    networks:
      - nexdom-net

networks:
  nexdom-net:
    driver: bridge
